Feat include news r fs and r ns
CodeTheApp/zeloclub-api pull request #21
Opened 2024-11-22 14:09 UTC by Poke-bits

2024-11-23 13:05 UTC, isaacviannadev requested changes

2024-11-23 19:55 UTC, Poke-bits commented on src/controllers/AuthController.ts
> +import { validateEmail, validatePassword } from "../util/validates";
ajustado!

2024-11-23 19:55 UTC, Poke-bits commented on src/controllers/AuthController.ts
> +import { faker } from "@faker-js/faker";
esta sendo usada agora, por uma outra alteracao que fiz

2024-11-23 19:55 UTC, Poke-bits commented on src/controllers/CareCharacteristicController.ts
> +        updatedAt: new Date(),
feito

2024-11-23 21:48 UTC, Poke-bits commented on src/middlewares/authMiddleware.ts
> +}
Uma interface para pegar o retorno da requisição, desmembrar o token e pegar as informações do usuário, como id e userType

2024-11-23 21:50 UTC, Poke-bits commented on src/util/validates.ts
> +  };
Removi a função deste arquivo, pois realmente era desnecessária.

2024-11-23 21:51 UTC, Poke-bits commented on src/controllers/UserController.ts
> +      console.log(token);
removido

2024-11-23 21:51 UTC, Poke-bits commented on src/schemas/ProfessionalProfile.ts
> +export const createProfessionalProfileSchema = z.object({
esta usando agora

2024-11-23 21:52 UTC, Poke-bits commented on src/schemas/Service.ts
> +export const createServiceSchema = z.object({
done

2024-11-23 21:52 UTC, Poke-bits commented on src/services/emailService.ts
> +
done

2024-11-23 21:53 UTC, Poke-bits commented on src/controllers/CareCharacteristicController.ts
> +
done

2024-11-23 21:53 UTC, Poke-bits commented on src/controllers/CareCharacteristicController.ts
> +          name: name || careCharacteristic.name,
done

2024-11-23 21:58 UTC, Poke-bits commented on src/controllers/UserController.ts
> +            avatar: newAvatarFilename,
nesse caso onde que esta fazendo o upload?
posso criar um ou ja tem pronto?

2024-11-23 21:58 UTC, Poke-bits commented on src/controllers/UserController.ts
> +          avatarUrl: newAvatarFilename,
nesse caso onde que esta fazendo o upload?
posso criar um ou ja tem pronto?

2024-11-24 12:21 UTC, isaacviannadev commented on src/controllers/UserController.ts
> +          avatarUrl: newAvatarFilename,
tem um arquivo em configs
`src/config/uploadConfig.ts`

ele quem faz o upload, é um middleware que faz o envio da imagem para o s3.

consegue ver ele na rota:
<img width="541" alt="image" src="https://github.com/user-attachments/assets/7f0ce200-6e6f-4a27-bf10-3a3d26c245ac">

<img width="541" alt="image" src="https://github.com/user-attachments/assets/93d4887b-5d0f-4cbd-b595-4622a1c569b8">

2024-11-24 12:47 UTC, closed without merging