Feat include zod validator in controller
CodeTheApp/zeloclub-api pull request #22
Opened 2024-11-22 19:20 UTC by Poke-bits

2024-11-23 13:31 UTC, isaacviannadev requested changes

2024-11-23 13:31 UTC, isaacviannadev commented on prisma/schema.prisma
> +  deletedAt   DateTime?
esse campo quando é opcional assim, ele não é incluido no objeto criado ou é criado como `null`?

2024-11-23 13:31 UTC, isaacviannadev commented on src/controllers/ApplicationController.ts
> +        return res
esse `return` não para execução?

2024-11-23 13:31 UTC, isaacviannadev commented on src/controllers/ApplicationController.ts
> +        "isaacsvianna@gmail.com",
alterar pra mandar para o email correto

2024-11-23 13:31 UTC, isaacviannadev commented on src/controllers/ApplicationController.ts
> +        return res
mesma questão sobre o return

2024-11-23 13:31 UTC, isaacviannadev commented on src/controllers/AuthController.ts
> +        logger.info("Request password reset", { email });
só organizar melhor esse código, pular linha onde precisa pra fica legível.

2024-11-23 13:31 UTC, isaacviannadev commented on src/controllers/AuthController.ts
> +        crypto.randomBytes(3).toString("hex");
define um padrão para isso, se vai ser o faker ou o crypto e elimina a não utilizada.
cuidado pra não criar lixo e dependências desnecessárias

2024-11-23 13:31 UTC, isaacviannadev commented on src/controllers/AuthController.ts
> +      ) {
isso aqui deveria estar sendo verificado pelo schema do zod

2024-11-23 13:31 UTC, isaacviannadev commented on src/controllers/ServiceController.ts
> +        where: { id,deletedAt: null },
formatacao

2024-11-23 18:44 UTC, Poke-bits commented on prisma/schema.prisma
> +  deletedAt   DateTime?
O campo opcional seria para ser passado como parâmetro na requisição. Ele sempre será criado como null, porém, quando for necessário modificar, criar etc, não será obrigatório passá-lo

2024-11-23 18:47 UTC, Poke-bits commented on src/controllers/ApplicationController.ts
> +        return res
Ele retorna o erro e não mata o servidor. Se eu lançar um throw, a execução continuará, mas não seria o correto, certo?

2024-11-23 18:56 UTC, Poke-bits commented on src/controllers/AuthController.ts
> +      ) {
Está sendo verificado pelo schema do Zod, então vou remover essa verificação adicional

2024-11-23 21:58 UTC, Poke-bits commented on src/controllers/ApplicationController.ts
> +        "isaacsvianna@gmail.com",
done

2024-11-23 21:59 UTC, Poke-bits commented on src/controllers/ApplicationController.ts
> +        return res
ajustado

2024-11-23 21:59 UTC, Poke-bits commented on src/controllers/AuthController.ts
> +        logger.info("Request password reset", { email });
done

2024-11-23 21:59 UTC, Poke-bits commented on src/controllers/AuthController.ts
> +        crypto.randomBytes(3).toString("hex");
retirei o crypto, vamos seguir de faker

2024-11-23 21:59 UTC, Poke-bits commented on src/controllers/ServiceController.ts
> +        where: { id,deletedAt: null },
done

2024-11-24 13:09 UTC, isaacviannadev requested changes

2024-11-24 13:09 UTC, isaacviannadev commented on src/controllers/AuthController.ts
> +
colocar um logger.info passando o user id

2024-11-24 13:09 UTC, isaacviannadev commented on src/controllers/CareCharacteristicController.ts
> +      const { name, description } = validationData.data ?? {};
passa essa linha para depois do if, acho que se não validar, não faz sentido desestruturar data.

2024-11-24 13:09 UTC, isaacviannadev commented on src/controllers/CareCharacteristicController.ts
> +        description: description?? '',
nao pode criar com nome e description vazios

2024-11-24 13:09 UTC, isaacviannadev commented on src/controllers/CareCharacteristicController.ts
> +      const { name, description, orderByName } = validationData.data ?? {};
o mesmo aqui

2024-11-24 13:50 UTC, isaacviannadev commented on src/controllers/ApplicationController.ts
> +        return res
se estiver dando certo, otimo.

mas vejo nos outros lugares o `return;` sozinho depois do `res.`...

2024-11-25 13:30 UTC, isaacviannadev approved these changes

2024-11-25 13:30 UTC, merged